markdown: kramdown
permalink: pretty
encoding: utf-8

exclude: [node_modules, ./bitwarden-help.sln]

collections:
  categories:
    output: true
    permalink: /:path/
  articles:
    output: true
    permalink: /:path/
