markdown: kramdown
highlighter: none
permalink: pretty
encoding: utf-8
port: 4009

sass:
  style: compressed

exclude:
  - node_modules
  - bitwarden-help.sln
  - package.json
  - package-lock.json
  - gulpfile.js
  - README.md

include: 
  - ".nojekyll"

collections:
  categories:
    output: true
    permalink: /:path/
  articles:
    output: true
    permalink: /article/:name/
