image:
- Ubuntu1804

branches:
  except:
    - gh-pages

stack: node 10, ruby 2.6.0

init:
- gem install jekyll bundler

before_build:
- node --version
- npm --version

build_script:
- npm install
- npm run deploy:ci
